version: "3.8"

# NOTE: for all of the images for the 5 microservices,
# you'll have to change the `image: <name>` part
# to whatever your image names are

services:
  caddy:
    image: alftirta/proxy-caddy:1.0.1
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
      - "3000:3000"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
  
  front-end:
    image: alftirta/front-end:1.0.11
    deploy:
      mode: replicated
      replicas: 1
    environment:
      - BROKER_URL=http://localhost:3000
  
  broker-service:
    image: alftirta/broker-service:1.0.1
    deploy:
      mode: replicated
      replicas: 1
  
  authentication-service:
    image: alftirta/authentication-service:1.0.1
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DSN: "host=postgresql port=5432 user=postgres password=password dbname=users sslmode=disable timezone=UTC connect_timeout=5"
  
  logger-service:
    image: alftirta/logger-service:1.0.0
    deploy:
      mode: replicated
      replicas: 1
  
  mail-service:
    image: alftirta/mail-service:1.0.0
    deploy:
      mode: replicated
      replicas: 1
    environment:
      MAIL_PORT: 1025
      MAIL_DOMAIN: localhost
      MAIL_HOST: mailhog
      MAIL_USERNAME: ""
      MAIL_PASSWORD: ""
      MAIL_ENCRYPTION: none
      MAIL_FROM_NAME: "John Smith"
      MAIL_FROM_ADDRESS: "john.smith@example.com"
  
  listener-service:
    image: alftirta/listener-service:1.0.0
    deploy:
      mode: replicated
      replicas: 1
  
  postgresql:
    image: 'postgres:14.2'
    ports:
      - "5432:5432"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
    volumes:
      - ./db-data/postgresql:/var/lib/postgresql/data
  
  mongodb:
    image: 'mongo:4.2.16-bionic'
    ports:
      - "27017:27017"
    deploy:
      mode: global
    environment:
      MONGO_INITDB_DATABASE: logs
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./db-data/mongodb:/data/db
  
  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
      - "8025:8025"
    deploy:
      mode: global
  
  rabbitmq:
    image: 'rabbitmq:latest'
    deploy:
      mode: global

volumes:
  caddy_data:
    external: true
  caddy_config:
